name: Push to Docker Hub

on: [workflow_dispatch]

jobs:
  backend-image:
    name: Build backend image
    runs-on: ubuntu-latest

    steps:
      - name: â˜ï¸ Checkout source
        uses: actions/checkout@v3
      - name: ğŸ”§ Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: ğŸ”§ Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      # - name: ğŸ‹ Login to Docker Hub
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: ğŸ“¦ Build backend and export to Docker
        uses: docker/build-push-action@v3
        with:
          load: true
          context: backend
          tags: egi-infisical/backend:test
      - name: â» Spawn backend container and dependencies
        run: |
          docker compose -f .github/resources/docker-compose.be-test.yml up -d
      - name: ğŸ§ª Test backend image
        run: |
          sh .github/resources/healthcheck.sh infisical-backend-test
      - name: â» Shut down backend container and dependencies
        run: |
          docker compose -f .github/resources/docker-compose.be-test.yml down
      - name: Test backend step
        run: |
          echo 'Test step succeeded'
      # -
      #   name: ğŸ—ï¸ Build backend and push
      #   uses: docker/build-push-action@v3
      #   with:
      #     push: true
      #     context: backend
      #     tags: infisical/backend:latest
      #     platforms: linux/amd64,linux/arm64

  # frontend-image:
  #   name: Build frontend image
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: â˜ï¸ Checkout source
  #       uses: actions/checkout@v3
  #     - name: ğŸ”§ Set up QEMU
  #       uses: docker/setup-qemu-action@v2
  #     - name: ğŸ”§ Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v2
  # - name: ğŸ‹ Login to Docker Hub
  #   uses: docker/login-action@v2
  #   with:
  #     username: ${{ secrets.DOCKERHUB_USERNAME }}
  #     password: ${{ secrets.DOCKERHUB_TOKEN }}
  # - name: ğŸ“¦ Build frontend and export to Docker
  #   uses: docker/build-push-action@v3
  #   with:
  #     load: true
  #     context: frontend
  #     tags: infisical/frontend:test
  #     build-args: |
  #       POSTHOG_API_KEY=${{ secrets.PUBLIC_POSTHOG_API_KEY }}
  # - name: ğŸ§ª Test frontend image
  #   run: |
  #     docker run --rm infisical/frontend:test
  # - name: Test frontend step
  #   run: |
  #     echo 'Test step succeeded'
  # -
  #   name: ğŸ—ï¸ Build frontend and push
  #   uses: docker/build-push-action@v3
  #   with:
  #     push: true
  #     context: frontend
  #     tags: infisical/frontend:latest
  #     platforms: linux/amd64,linux/arm64
  #     build-args: |
  #       POSTHOG_API_KEY=${{ secrets.PUBLIC_POSTHOG_API_KEY }}
